# Generated by Django 2.0.4 on 2018-04-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emailaddress', models.CharField(max_length=30)),
                ('phoneNumber', models.IntegerField(max_length=15)),
            ],
        ),
    ]
